### ISSUE TITLE
books.imhonet.ru

### ISSUE THREAD

**Issue by chkrn** [idlesign/imhodump#2]
А под каталог книг имхонета сложно будет переделать? :)

Сейчас валится на первой же книге, к примеру:

```
$ python imhodump_books.py 

Страница http://idle.imhonet.ru/content/books/rates/all/ ...
Обработка Алебардщик Малого Райншлосса ...
Traceback (most recent call last):
  File "imhodump_books.py", line 97, in <module>
    pickle.dump(get_rates(URL_RATES_ALL, True), f)
  File "imhodump_books.py", line 55, in get_rates
    info = rate_box.xpath("div[@class='content']/div[@class='info']/div[@class='country']")[0]
IndexError: list index out of range
```

**Comment by idlesign** [comment]
Закрываю. См. #8
Разборщик обновлён под разметку раздела Фильмы. 
Разбор Книг не пробовал, но наверняка не работает..
